" ============================================================================
" FCT syntax highlighting
"
" To install:
"   1. Copy this block into your ~/.vimrc (or ~/.config/nvim/init.vim).
"   2. Restart Vim/Neovim.
"
" Files ending in .fct will automatically use this syntax highlighting.
" ============================================================================

" Detect .fct files
augroup fct_filetype
  autocmd!
  autocmd BufRead,BufNewFile *.fct setfiletype fct
augroup END

" Define FCT syntax
augroup fct_syntax
  autocmd!
  autocmd FileType fct call s:DefineFctSyntax()
augroup END

function! s:DefineFctSyntax() abort
  syntax clear

  " Whole line comments
  syntax match fctComment "^\s*#.*$"

  " Assignment keywords (only when followed by '=')
  syntax match fctAssignmentKeyword
        \ "^\s*\zs\%(vector\|config\|load-low\|toggles\|load-low-margin\|load-high\|load-high-margin\|load-current\|load-current-margin\|input-current-margin\|input-voltage-high\|input-current-high\|input-voltage-low\|input-current-low\|output-drive\|output-drive-strength\|output-voltage-high\|output-voltage-margin\)\ze\s*="

  " Single quoted assignment values
  syntax region fctAssignmentValue
        \ start=/'/
        \ end=/'/
        \ contained

  " Assignment lines
  syntax match fctAssignmentLine
        \ "^\s*\%(vector\|config\|load-low\|toggles\|load-low-margin\|load-high\|load-high-margin\|load-current\|load-current-margin\|input-current-margin\|input-voltage-high\|input-current-high\|input-voltage-low\|input-current-low\|output-drive\|output-drive-strength\|output-voltage-high\|output-voltage-margin\)\s*=.*$"
        \ contains=fctAssignmentKeyword,fctAssignmentValue

  " Highlight groups
  highlight default link fctComment Comment
  highlight default link fctAssignmentKeyword Keyword
  highlight default link fctAssignmentValue String

  let b:current_syntax = "fct"
endfunction
